run:
  timeout: 5m

issues:
  exclude-dirs:
    - testdata

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
